"""FastAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RByvo_ZNZCOgwl9L_lte9rb8QjYPoR0B

"""


from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok, conf
import uvicorn
import getpass


json_data = [
    {
       "number": 3,
       "name": "Edward",
       "age": 30,
       "city": "Madrid",
       "country": "Spain"
    },
    {
       "number": 10,
       "name": "July",
       "age": 27,
       "city": "London",
       "country": "United Kingdom"
    },
    {
       "number": 10,
       "name": "Monica",
       "age": 41,
       "city": "Los Angeles",
       "country": "United States of America"
    }
]

app = FastAPI()

@app.get('/index')
async def home():
  return json_data

conf.get_default().auth_token = getpass.getpass()
ngrok_tunnel = ngrok.connect(8000)
print('Public URL:', ngrok_tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port=8000)
